### ISSUE TITLE
nanocbor_enter_array() does not return NANOCBOR_OK on success

### ISSUE THREAD

**Issue by benpicco** [bergzand/NanoCBOR#26]
The documentation states

> ` * @return              NANOCBOR_OK on success`

`NANOCBOR_OK` is defined to be 0.

However, `nanocbor_enter_array()` returns the result of `_enter_container()` which return 1 on success.

Checking the return value of `nanocbor_enter_array()` to match `NANOCBOR_OK` will therefore always fail.

**Comment by bergzand** [comment]
Fixed with #34
